# Model arguments
model_name_or_path: /home/wnq/pp1/code/sft-outputs/llama-3.1-base-sft/checkpoint-4872
torch_dtype: null
attn_implementation: flash_attention_2

# from disk:
file_type: "parquet"
path: /home/data_root
disk_mixer:
  train: train_filename
  test:  test_filename

# SimPOTrainer arguments
bf16: true
beta: 0.1
# gamma_beta_ratio: 0.5
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: pdpo-exps
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: sft-outputs/llama-3-8b-base-pdpo-v7
run_name: llama-3-8b-base-pdpo
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- none
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
sample_ratio_r1: 0.7